### ISSUE TITLE
Support building with the OpenJDK 1.8 class library

### ISSUE THREAD

**Issue by dwijnand** [ReadyTalk/avian#410]
I'm getting errors when trying to build with the OpenJDK class library, when using 1.8 (using 1.8.0_31 at the moment), see:

```
$ /usr/libexec/java_home
/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home
$ export JAVA_HOME=$(/usr/libexec/java_home)
$ make openjdk=/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home
compiling build/macosx-x86_64-openjdk/tools/type-generator/main-build.o
compiling build/macosx-x86_64-openjdk/system/posix-build.o
compiling build/macosx-x86_64-openjdk/system/posix/crash-build.o
compiling build/macosx-x86_64-openjdk/system/posix/memory-build.o
compiling build/macosx-x86_64-openjdk/system/posix/signal-build.o
compiling build/macosx-x86_64-openjdk/finder-build.o
compiling build/macosx-x86_64-openjdk/util/arg-parser-build.o
linking build/macosx-x86_64-openjdk/generator
compiling classpath classes
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
generating build/macosx-x86_64-openjdk/type-enums.cpp
generating build/macosx-x86_64-openjdk/type-declarations.cpp
generating build/macosx-x86_64-openjdk/type-constructors.cpp
generating build/macosx-x86_64-openjdk/type-initializations.cpp
generating build/macosx-x86_64-openjdk/type-java-initializations.cpp
generating build/macosx-x86_64-openjdk/type-name-initializations.cpp
generating build/macosx-x86_64-openjdk/type-maps.cpp
compiling build/macosx-x86_64-openjdk/system/posix.o
compiling build/macosx-x86_64-openjdk/system/posix/crash.o
compiling build/macosx-x86_64-openjdk/system/posix/memory.o
compiling build/macosx-x86_64-openjdk/system/posix/signal.o
compiling build/macosx-x86_64-openjdk/finder.o
compiling build/macosx-x86_64-openjdk/machine.o
compiling build/macosx-x86_64-openjdk/util.o
compiling build/macosx-x86_64-openjdk/heap/heap.o
compiling build/macosx-x86_64-openjdk/compile.o
compiling build/macosx-x86_64-openjdk/classpath-openjdk.o
src/classpath-openjdk.cpp:2389:10: error: no matching function for call to 'makeJmethod'
  return makeJmethod(t,
         ^~~~~~~~~~~
build/macosx-x86_64-openjdk/type-declarations.cpp:5676:12: note: candidate function not viable: cannot convert from base class
      pointer 'object' (aka 'vm::GcObject *') to derived class pointer 'vm::GcJclass *' for 7th argument
GcJmethod* makeJmethod(Thread* t, uint8_t override, object securityCheckCache, uint8_t hasRealParameterData, object paramet...
           ^
src/classpath-openjdk.cpp:2370:8: note: candidate function not viable: requires 18 arguments, but 20 were provided
object makeJmethod(Thread* t,
       ^
src/classpath-openjdk.cpp:293:8: note: candidate function not viable: requires at most 3 arguments, but 20 were provided
object makeJmethod(Thread* t, GcMethod* vmMethod, int index = -1);
       ^
src/classpath-openjdk.cpp:2427:10: error: no matching function for call to 'makeJconstructor'
  return makeJconstructor(t,
         ^~~~~~~~~~~~~~~~
build/macosx-x86_64-openjdk/type-declarations.cpp:5662:17: note: candidate function not viable: cannot convert from base class
      pointer 'object' (aka 'vm::GcObject *') to derived class pointer 'vm::GcJclass *' for 7th argument
GcJconstructor* makeJconstructor(Thread* t, uint8_t override, object securityCheckCache, uint8_t hasRealParameterData, obje...
                ^
src/classpath-openjdk.cpp:2411:8: note: candidate function not viable: requires 15 arguments, but 17 were provided
object makeJconstructor(Thread* t,
       ^
src/classpath-openjdk.cpp:295:8: note: candidate function not viable: requires at most 3 arguments, but 17 were provided
object makeJconstructor(Thread* t, GcMethod* vmMethod, int index = -1);
       ^
2 errors generated.
make: *** [build/macosx-x86_64-openjdk/classpath-openjdk.o] Error 1
```

**Comment by dwijnand** [comment]
I meant to add: It works with 1.7.0_65
